In [1]:
from quokka_process import process_file
from pathlib import Path
import numpy as np

In [2]:
process_file(
    282637,               # number of NeXUS file
    25,                   # frame frequency (Hz)
    25,                   # How many frames does one oscillation of SE take?
    5.0,                  # subframe_bin_sz (ms), divides frame period into smaller sections, if you think you have faster kinetics
    50,                   # splits SE oscillation [0, 2 * pi] into this many datasets
    Path("."), # Path to NeXUS file
    Path("."),   # Path to NEF
    Path("."),    # Path to SEF,
    collect_time=(10800, 21000),
    debug=True
)

Processing QKK0282637.nx.hdf, daq_dirname='DAQ_2025-11-27T00-27-12'
Obtaining NEF/SEF and merging
loading SEF
array search: 47, nearest time: 47
deglitching
Loading NEF, finding phase
[ 1.6346927   0.0733355   6.92774951 24.99986083] 6.3607082277967475
[ 1.63457081  0.0728927   5.88285927 24.99997117] 6.4769470116222
[ 1.63445331  0.07312762 10.71716091 24.99955657] 6.306103594499426
[ 1.63495574  0.07303648 12.69398284 24.99941241] 6.433004954492882
[ 1.63479912  0.07258646  3.09394828 25.00022036] 6.49818574649713
[ 1.63432715  0.07327338  2.64755712 25.00026037] 6.3949589845866015
[ 1.63497314  0.0733441  24.60093145 25.0004967 ] 6.477322685466973
[ 1.63437902  0.07177974 24.76119668 25.00047895] 6.402785187925075
[ 1.63483295  0.07244433  0.9087091  25.00038876] 6.207896969737428
[ 1.63536136  0.07280764  8.70347474 24.9998153 ] 6.5196015461176495
[ 1.63543024  0.07331234  4.91369353 25.00009378] 6.4111507036449655
[ 1.63555803  0.07298542  9.92620524 24.99974684] 6.262082000716357